apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-fast-repl
provisioner: docker.io/hostpath
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
#allowedTopologies:
#- matchLabelExpressions:
#  - key: topology.kubernetes.io/zone
#    values:
#    - europe-west2-b
#    - europe-west2-c